name: memory_estimator
description: A command-line application for memory estimation.
version: 0.1.0-rc1
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  args: ^2.4.2
  webapp_core:
#    path: ../webapp_lib/webapp_core
    git:
      url: https://github.com/tercen/webapp_lib.git
      ref: main
      path: webapp_core

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

# Configure as an executable
executables:
  memory_estimator:
